version: "3.5"

services:
    app:
        build:
            context: .
        expose:
            - 5000
        volumes:
            - .:/app:ro
            - /data/tagit:/data
        command: /usr/local/bin/gunicorn -k gevent --reload --workers 5 --worker-connections 100 --access-logfile=- --pythonpath /app -b :5000 app:app

    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "8082:8080"
        volumes:
            - ./static:/www/static:ro
            - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf

#volumes:
#    data:
